document.writeln("<div class=\"main\">");
document.writeln("	<h1>最新门牌</h1>");
document.writeln("	<div class=\"content\">");
document.writeln("		<div class=\"content-top\">");
document.writeln("			<h2>mmbd.com</h2>");
document.writeln("			<ul>");
document.writeln("								<li>请点击以下域名访问网站</li>");
document.writeln("				<li>m.dogtop.xyz</li>");
document.writeln("				<li>m.doglive.xyz</li>");
document.writeln("				<li>国产浏览器屏蔽网站严重，最好请用以下浏览器：<br><a href=\"https://www.google.cn/chrome/\" target=\"_blank\">Chrome</a>　　<a href=\"https://www.mozilla.org/zh-CN/firefox/\" target=\"_blank\">Firefox</a>　　<a href=\"https://www.microsoftedgeinsider.com/zh-cn/download/\" target=\"_blank\">Edge</a>　　<a href=\"https://viayoo.com/zh-cn/\" target=\"_blank\">Via</a>　　<a href=\"https://www.xbext.com/\" target=\"_blank\">X</a></li>");
document.writeln("			</ul>");
document.writeln("			<p>如果以上地址均无法打开，欢迎发送邮件告知： <br><span class=\"glyphicon glyphicon-user\"></span> 联系客服mmbadcom@gmail.com");
document.writeln("			</p>");
document.writeln("		</div>");
document.writeln("	</div>");
document.writeln("</div>");
