document.writeln("	<div class=\"main\">");
document.writeln("		<h1>BZHAN</h1>");
document.writeln("		<div class=\"content\">");
document.writeln("			<div class=\"content-top\">				");
document.writeln("					<h2>不定期更换域名，请收藏发布页！</h2>");
document.writeln("					<h2><span style=\"color:#FFE500;font-size:20px;\">勿用QQ/UC/360/夸克等浏览器</span></h2>");
document.writeln("					<ul>");
document.writeln("						<li>");
document.writeln("						    <br><span>如果长时间未响应,尝试刷新浏览器</span>");
document.writeln("							<span style=\"font-size:32px;background-color:#FFE500;color:#000000;\"><a href=\"https://m.doglive.xyz/forum.php\" id=\"rowid1\" onclick=\"changeurl();\"><i><b>=点击进入论坛1=</b></i></a></span><br>");
document.writeln("							<span style=\"font-size:32px;background-color:#FFE500;color:#000000;\"><a href=\"https://m.dogtop.xyz/forum.php\" id=\"rowid1\" onclick=\"changeurl();\"><i><b>=点击进入论坛2=</b></i></a></span>");
document.writeln("							<p align=\"center\"><font color=\"#FF0000\"><b>警告 / WARNING </b>");
document.writeln("</font><br>");
document.writeln("请使用原版EDGE Chrome 火狐等原版浏览器，避免无法访问！APP无法访问清空缓存即可！<br>");
document.writeln("						</p></li>");
document.writeln("						<li>");
document.writeln("						新门牌获取地址：访问不了尝试刷新！<br>");
document.writeln("							<i>[i996.cc][u996.cc][z996.cc]</i>");
document.writeln("						</span></span></li>");
document.writeln("						<li>");
document.writeln("					<a href=\"https://www.microsoft.com/zh-cn/edge\" target=\"_blank\">EDGE浏览器</a>　　　<a href=\"https://www.mozilla.org/zh-CN/firefox/\" target=\"_blank\">Firefox浏览器</a><br>");
document.writeln("							<span>永久地址获取邮箱：mmbadcom@gmail.com<span>");
document.writeln("						</span></span></li>");
document.writeln("					</ul>");
document.writeln("			</div>");
document.writeln("		</div>");
document.writeln("		<p class=\"footer\">© 2022 All Rights Reserved</p>");
document.writeln("	</div>");
